[[profile]]
name = "Home Workroom"
exec = ["notify-send shikane \"Monitor profile $SHIKANE_PROFILE_NAME has been applied\""]

    [[profile.output]]
    match = "/.*U32R59x H4ZNC03013.*/"
    enable = true
    mode = { width = 3840, height = 2160, refresh = 30 }
    position = { x = 1920, y = 0 }
    scale = 1.5

    [[profile.output]]
    match = "/.*eDP-1.*/"
    enable = true
    mode = { width = 1920, height = 1080, refresh = 60 }
    position = { x = 0, y = 0 }
    scale = 1.0
